mixtral_optimised = "ybelkada/Mixtral-8x7B-Instruct-v0.1-bnb-4bit"
phixtral = "mlabonne/phixtral-2x2_8"
big_phixtral = "mlabonne/phixtral-4x2_8"
neural_beagle = "mlabonne/NeuralBeagle14-7B"
mistral = "mistralai/Mistral-7B-Instruct-v0.2"
jellyfish = "NECOUDBFM/Jellyfish"
tableLlama = "osunlp/TableLlama"
phi3 = "microsoft/Phi-3-mini-128k-instruct"